# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 130
  tables: false

# MD041/first-line-heading/first-line-h1 - First line in a file should be a top-level heading
MD041:
  # Heading level
  level: 1
