GLOBAL_PROPERTIES = [
    "item",
    "store",
    "display_name",
    # "pickup_location",
    "items_available",
    # "distance",
    "favorite",
    # "in_sales_window",
    # "new_item",
]
STORE_PROPERTIES = [
    "store_id",
    # "store_name",
    # "description",
    # "tax_identifier",
    # "website",
    # "store_location",
    # "logo_picture",
    # "store_time_zone",
    # "hidden",
    # "favorite_count",
    # "items",
    # "milestones",
    # "we_care",
]
ITEM_PROPERTIES = [
    "item_id",
    # "price",
    # "sales_taxes",
    # "tax_amount",
    # "price_excluding_taxes",
    "price_including_taxes",
    # "average_overall_rating",
    # "value_excluding_taxes",
    # "value_including_taxes",
    # "taxation_policy",
    # "show_sales_taxes",
    # "cover_picture",
    # "logo_picture",
    # "name",
    # "description",
    # "can_user_supply_packaging",
    # "packaging_option",
    # "diet_categories",
    # "item_category",
    # "badges",
    # "positive_rating_reasons",
    # "favorite_count",
    # "buffet",
]
PRICE_PROPERTIES = [
    "code",
    "minor_units",
    "decimals"
]
